# Friday Sept 11: What is a population?

For the questions below, submit your answers to Brightspace ideally before the next class. The deadline to submit your answers is Friday Sept 18.

The _Resources_ below are sufficient to answer all the questions, however, you are encouraged to find your own textbooks or peer-reviewed articles to answer the questions if you feel comfortable. You can search for textbooks using and the [library catalogue](https://www.library.mun.ca/) and peer-reviewed articles using [Web of Science](https://apps-webofknowledge-com.qe2a-proxy.mun.ca/WOS_GeneralSearch_input.do?product=WOS&search_mode=GeneralSearch&SID=5COlVVH7qj2puc72yvk&preferencesSaved=).

## Questions

1. Give a definition of a population from a textbook or peer-reviewed publication. Provide the citation. [2 marks]

1. Find a peer-reviewed paper where a population is studied. Write 1 paragraph discussing how a population is defined for the study and how this compares to your definition of a population given in Question 1. [5 marks]

## Resources

Vandermeer, J.H., Goldberg, D.E., 2013. Population Ecology: First Principles (Second Edition). Princeton University Press, Princeton, United States. [Link](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/mun/detail.action?docID=1205619)

The Princeton Guide to Ecology, edited by Simon A. Levin, et al., Princeton University Press, 2009. ProQuest Ebook Central, [Link](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/mun/detail.action?docID=557123)

Sacchi, R., Gentilli, A., Razzetti, E., Barbieri, F., 2002. Effects of building features on density and flock distribution of feral pigeons Columba livia var. domestica in an urban environment. Can. J. Zool. 80, 48-54. [Link](https://doi.org/10.1139/z01-202)
