# Tues Sept 15: Exponential growth - discrete time

Please submit your answers before the next class. You have until Tues Sept 22 to submit your answers.

## Required reading
Vandermeer, J.H., Goldberg, D.E., 2013. Population Ecology: First Principles (Second Edition). Princeton University Press, Princeton, United States. p1-3. [Link](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/mun/detail.action?docID=1205619)

## Questions

1. Suppose $\lambda = 5$ in equation (3) (see the required reading). Explain in 1-2 sentences the meaning of $\lambda = 5$. [1 mark]

2. Suppose the number of lilypads during week 7 is 78,125. Let $\lambda = 5$, and assume that the units of $t$ are weeks. Use equation (3) to calculate the number of lilypads in week 8. Show your calculations. [2 marks]

3. Use your answer to question 2. to calculate the number of lilypads in week 9. Show your calculations. [2 marks]

4. Equation (4) for the required reading assumes that $N_0=1$, however, this formula can be generalized such that

\[
N_t = N_0\lambda^t
\]

where $N_t$ is the population size at time, $t$. Define time such that $t=0$ is week 7 and $t$ is then the number of weeks since week 7. Use the equation above to answer question 3 and confirm that the answer is the same (i.e., find the population size for week 9, when $\lambda=5$ and the population size for week 7 is 78,125). Show your calculations. [2 marks]

5. Use the formula from question 4 to find the population size for week 15, where $N_0=1$ and $\lambda=5$. <span style="color: red;">Define time as the number of weeks since week 0</span>. Show your calculations [2 marks]

6. It is important to note that all mathematical formulas should have the same units on both sides of the equals sign, and for each term that is added or subtracted. The units of the population size, $N_t$, at time, $t$, are number. The geometric growth rate, $\lambda$ is unitless. Choose an equation from the required reading and give the units for each of the terms to show that both sides of the equals have the same units. For example, for the equation that appears in question 4, we have:

\begin{eqnarray*}
N_t & = & N_0 \lambda^t \\
\left(\mbox{number}\right)& =&(\mbox{number}) (\mbox{unitless})^{weeks}\\
\left(\mbox{number}\right)& =& \left(\mbox{number}\right)\\
\end{eqnarray*}

Note that:
\begin{eqnarray*}
(\mbox{unitless}) \times (\mbox{quantity with units}) & = & (\mbox{quantity with units}) \\ (\mbox{unitless})^{(\mbox{quantity})}& =& (\mbox{unitless})
\end{eqnarray*}
[2 marks]

7. Although not stated in the reading, $\lambda = 1 + b - d$ where $b$ is the per capita birth rate over one time step (i.e. one week for this example), and $d$ is the fraction of the lilypad population that dies over one time step. The number 1 is considered unitless, what must the units of $b$ and $d$ be? [1 mark]

8. In the reading, $\lambda = 2$. Given that $\lambda = 1 + b - d$, what are some possible values of $b$ and $d$. <span style="color: red;">Note that $d$ is a fraction and must be $1 \geq d \geq 0$ and $b>0$.</span> [1 mark]

9. [True or False] For discrete time exponential growth (as per the reading), the change in population size from one week to the next depends not so much on the per capita birth rate, but on the difference between the per capita birth rate and the per capita death rate. [1 mark]
