# Fri Feb 11: Age-structured population dynamics

DUE DATE: Feb 18

## Required Reading
Read over yesterdays material

## Questions

1. For the Leslie matrix from last class:

\begin{equation}
\mathbb{A}=
\left[
\begin{array}{cc}
0 & 2\\
0.5 & 0.2\\
\end{array}
\right]
\end{equation}

the stable stage distribution is: $[0.644, 0.356]^T$, which means that when the population has 64.4% young-of-the-year frogs, and 35.6% frogs one year or older, each year both age classes will increase by a fixed amount which is the dominant eigenvalue that you calculated for yesterday's question 1.

Check that this is true. Let,

\begin{equation}
\vec{N}_t = 
\left[
\begin{array}{c}
64.4\\
35.6\\
\end{array}
\right].
\end{equation}

a. Calculate $\vec{N}_{t+1} = \mathbb{A}\vec{N}_{t}$ (remember to use matrix multiplication). [1 mark]

b. Calculate the increase from $t$ to $t+1$ for both stages, i.e., $f_1 = N_{1,t+1}/64.4$ and $f_2 = N_{2,t+1}/35.6$. How do $f_1$ and $f_2$ compare to the dominant eigenvalue that you calculated for yesterday's question 1? [2 marks]

2. Now let's choose $\vec{N}_t$ such that it is not the stable stage structure values. Let, $\vec{N}_0 = [50 50]$. Using the same Leslie matrix, $\mathbb{A}$, do the matrix multiplication to calculate $\vec{N}_1$, $\vec{N}_2$, and $\vec{N}_3$ (remember that $\vec{N}_t$ is a vector containing two values). [3 marks]

3. For you answer to 2. calculate $f_{1,t} = N_{1,t+1}/N_{1,t}$ and $f_{2,t} = N_{2,t+1}/N_{2,t}$ for $t=0,1,2$. Are these values getting closer to the dominant eigenvalue of $\mathbb{A}$ as $t$ gets larger? [2 marks]
