# Fri Feb 18: Density dependence in age-structured models 

DUE: Fri Feb 25

## Required Reading
Vandermeer, J.H., Goldberg, D.E., 2013. Population Ecology: First Principles (Second Edition). Princeton University Press, Princeton, United States. p48-50. [Link](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/mun/detail.action?docID=1205619)

All of the population models that we have seen to date give exponential growth or decay because they do not have any density dependence. However, it is possible to include density dependence in models with stage structure.

Consider the model described in the required reading. For today's lab we will write an R Script to solve this model and reproduce the graph figure 2.4.

```{r}
# Upper limit on reproduction
r<-3.3
# Proportion of larvae that become adults
p<-0.95
# index corresponding to a position in a vector (as list)
i=1
# time values
times = seq(0,30,1)
T = length(times)
# Preallocation of X: larvae, and Y: adults
X = rep(0,T)
Y = rep(0,T)
# Initial values at t=0
X[1] = 0.01
Y[1] = 0.01
# The for loop calculations the next values: X[t+1] and Y[t+1] from
# the current values, X[t] and Y[t], for each of the values of time, t,
# sequentially
for(t in head(times,-1)){
  # Equations 28a and 28b in Vandermeer and Goldbert
  X[i+1]=r*Y[i]*(1-Y[i]/r)
  Y[i+1]=p*X[i]
  # advance to the next value of time
  i=i+1
}
# graph the results
#plot(times,X+Y, typ = "l")
#plot(times,X, typ = "l")
#lines(times,Y,typ="l", lwd=2)
```

## Questions
1. What is true about exponential growth relative to density-dependent growth for a stage structured  model? When are they the same [1 mark]

2. Explain how density dependence affects the larvae-adult population as described by equations 28a and b: is the production of larvae or adults affected by density dependence? Does resource competition affect fecundity, mortality, or maturation, of larvae or adults? [2 marks]

3. Give a value of $r$ where equations 28a and b produce cyclic population dynamics? [1 mark]

4. Run the code above in R or watch Dr. Hurford's lecture. When the population cycles, how to the larvae and adults cycle relative to each other? [1 mark]
