--- 
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: false 
---

# Tues Jan 11: Syllabus
 
## Instructor Information

Instructor: Dr. Amy Hurford\
Office: Teaching remotely\
Email: ahurford@mun.ca\
I will try to reply to emails within 24 hours (excluding evenings, weekends and holidays). I am always available during the lecture times. Please email to request a meeting for a different time. Please check my [schedule](https://ahurford.github.io/website/#dr.-amy-hurford) and suggest a time I am free that works for you.

## Course Information	
TR 12.00-12.50pm\
F 1-1.50pm\

- When the university is online: See course Brightspace under Announcements for WebEx link.
- When the university is in-person: SN3060

R Lab 2-5pm \

- When the university is online: See course Brightspace under Announcements for WebEx link.\
- When the university is in-person: CSF 2218 (capacity is 9 computers provided) and 2342 (bring your own laptop). 

Course description:\
Population and Evolutionary Ecology is an introduction to the theory and principles of evolutionary ecology and population dynamics. Pre-requisites: BIOL 2600; at least one of BIOL 2010, 2122 or 2210.\
	
Course format:\
The course has been re-designed for online delivery. Specifically, no exams that require invigilation are part of the grading scheme because these are challenging to deliver remotely. Pre-recorded lectures limit my ability to interact with students. Therefore, I have elected to dedicate all lecture time to interacting with students. For each class there is a list of questions you are required to answer and hand-in. Prior to some classes there may be a _Required Reading_, that if completed will allow you to answer the day's assignment questions. Prior to the day of class you should complete the _Required Reading_. In addition, I can most effectively help you if you have read over the questions ahead of time.

When the university is remote (i.e. lectures are remote), labs will also be remote.

Labs will be:

- January 20

- February 3

- February 17

- March 3

- March 17

- March 31

Course will follow a similar format if the university returns to in-person lectures. If this is the case, I will give short lectures at the beginning of each class which cover the material in the assigned pre-lecture readings.

Course expectations:\
Any students that are disruptive, violating university policies, or acting in a potentially unsafe way will be warned and asked to leave.\
	    
Learning goals:\
I consider your completed assignments to be a portfolio of your knowledge in population and evolutionary ecology. You will also get some exposure to coding in `R`. It takes time to become proficient in a programming language, but the time you will spend coding in this class will help you towards becoming more proficient. The course content emphasizes a deeper understanding of fewer concepts. You have the opportunity to further explore a topic of interest to you for the final project.

Required Text and Resources:\
The course materials are online at https://ahurford.github.io/BIOL-3295-Winter-2022/. In addition you will need a computer to install `R` and `RStudio`. This will be covered on Thursday January 20 in lab (see also [here](https://ahurford.github.io/quant-guide-all-courses/install.html)). Class announcements and WebEx links will be provided on the course BrightSpace and your assignments are to be submitted to BrightSpace.

## Method of Evaluation

- 35 assignments, every lecture except the first (equal weighting) - 50%
- 6 labs (equal weighting) - 20%
- Takehome midterm (due Thursday March 3 at 9am) - 10%
- Final Project (due Wednesday April 20 at 9am) - 20%

You should aim to complete each assignment before the next class, but assignments will be accepted, without penalty, up to a week later. You will have 2 weeks to complete the midterm.

Late assignments, labs, and missed midterms, and final exams will be accommodated as described by University Regulation 6.7.3 and 6.7.5 (see [https://www.mun.ca/regoff/calendar/sectionNo=REGS-0474](https://www.mun.ca/regoff/calendar/sectionNo=REGS-0474) for Regulations).

## Additional Policies
### Accommodation of students with disabilities
Memorial University of Newfoundland is committed to supporting inclusive education based on the principles of equity, accessibility and collaboration. Accommodations are provided within the scope of the University Policies for the Accommodations for Students with Disabilities see [www.mun.ca/policy/site/policy.php?id=239](www.mun.ca/policy/site/policy.php?id=239). Students who may need an academic accommodation are asked to initiate the request with the Glenn Roy Blundon Centre at the earliest opportunity (see [www.mun.ca/blundon](www.mun.ca/blundon) for more information). 

### Academic misconduct
Students are expected to adhere to those principles, which constitute proper academic conduct. A student has the responsibility to know which actions, as described under Academic Offences in the University Regulations, could be construed as dishonest or improper. Students found guilty of an academic offence may be subject to a number of penalties commensurate with the offence including reprimand, reduction of grade, probation, suspension or expulsion from the University. For more information regarding this policy, students should refer to University Regulation 6.12. 

### Equity and Diversity
A safe learning environment will be provided for all students regardless of race, colour, nationality, ethnic origin, social origin, religious creed, religion, age, disability, disfigurement, sex (including pregnancy), sexual orientation, gender identity, gender expression, marital status, family status, source of income or political opinion.

You should not photograph or record myself, teaching assistants, or other students in the class without first obtaining permission. Accommodation will be made for students with special needs.

The sound should be turned off on phones and computers during class.

## Additional Supports
Resources for additional support can be found at:

- [www.mun.ca/currentstudents/student/](www.mun.ca/currentstudents/student/)

- [https://munsu.ca/resource-centres/](https://munsu.ca/resource-centres/)

## Tentative course schedule
The course schedule is found in the toolbar of the class materials, see https://ahurford.github.io/BIOL-3295-Fall-2020/.

The last day to drop the course without academic prejudice is Wednesday Nov. 4.

## Handing in your work

### Making figures to hand-in {#figures}
The graphs you hand in need to have descriptive axeses and a figure caption. You may put these elements together using a word processing software such as _Microsoft Word_. Elements of a good figure caption:

- Has a label, i.e., "Figure 1",

- The first sentences provides a summary of what the figure shows, i.e., "The price of oranges has increased steadily since 1964",

- Provide all necessary information to understand everything in the figure, i.e., if the figure has no legend, but multiple line types/symbols, be sure to indicate what is represented by the different symbols. If the axes labels are overly brief due to space constraints in the graph, provide a more thorough description in the figure caption. If any assumptions have been made in making the figure, disclose these, i.e., a point that was excluded from the analysis due to being considered an outlier.

### Writing R scripts to hand-in {#RScript}
To write your own R scripts follow the guidelines described in Chapter 7 [Best Practices](https://ahurford.github.io/quant-guide-all-courses/style.html) of _Quantitative training in Biology_. If you are asked to hand in your R script this means you need to submit an `.R` file on Brightspace.

