# Thurs Nov 5: Evolutionary ecology

DUE DATE: Thursday Nov 12.

This [link](https://www.zoology.ubc.ca/~bio418/) contains the course information for an evolutionary ecology class at UBC.

## Questions
1. Choose one of the topics and read enough about that topic to be able to write 1 paragraph explaining what that topic is about. Please make sure that your paragraph includes clear definitions of the relevant terms.

List the sources of information that you read to learn about the topic. You may choose the UBC lecture slides, the UBC readings, Wikipedia, books from the library on evolutionary ecology, or peer-reviewed journal articles.

[10 marks]

## Some relevant textbooks

Big problems in ecology and evolution by Sherratt and Wilkinson. [Link](https://ebookcentral.proquest.com/lib/mun/reader.action?docID=430616&ppg=136).

Evolutionary ecology: concepts and case studies by Fox, Roff, and Fairbairn [Link](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/mun/detail.action?docID=430289)




