# Fri Nov 6: Evolutionary ecology

DUE DATE: Fri Nov 13

## Required reading
Otto, Sarah P., and Troy Day. 2007. A Biologist's Guide to Mathematical Modeling in Ecology and Evolution, Princeton University Press. Beginning at 3.3 on p76 and ending at p82.  [Link](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/MUN/detail.action?docID=768551).

## Questions
1. What are population-genetic models? [1 mark]

2. Consider the definition of [population dynamics](https://en.wikipedia.org/wiki/Population_dynamics). How are population dynamics related to population-genetic models? You will need to mention inheritance in your answer. [2 marks]

3. What type of population growth is described by equations 3.6a and 3.6b? [1 mark]

4. Typically, in this course, we have used $\lambda$ to be the geometric growth rate. What are $W_A$ and $W_a$ in equations 3.6a and b, and for what values of $W_A$ and $W_a$ is the number of individuals with the $A$ and $a$ alleles increasing? [2 marks]

5. What are $n_A(t)$ and $n_a(t)$ in equations 3.6a and b? [1 mark]

6. What formula would you use to calculate the frequency of the $A$ allele at time, $t$? [1 mark]

7. Give *two* versions of a formula that you would use to calculate the frequency of the allele $A$ at time, $t+1$? [2 marks]

8. In equation 3.8d, what is $p(t+1)$ and what is $V_A$? [1 mark]

9. If $V_A > 1$, what does this imply about the geometric growth rates for individuals that inherit the $A$ allele relative to those that inherit the $a$ allele? [1 mark]

10. Using calculus, the author's derive a continuous time equation (3.11b) from the discrete time equation 3.8d. What is the formula for $s_c$? Provide the meaning of all parameters in your equation for $s_c$. [2 marks]

11. Although not provided in the book, for the continuous time version of this population-genetic model, the equations for the number of individuals with each allele would be,

\begin{eqnarray}
\frac{dn_A(t)}{dt} & = & r_A n_A(t) \\
\frac{dn_a(t)}{dt} & = & r_a n_a(t)
\end{eqnarray}

where $r_A = b_A - d_A$ and $r_a = b_a - d_a$, with $b_i$ the per capita birth rate, and $d_i$ the per capita mortality rate for each of the $A$ and $a$ alleles respectively. If $r_A > 0$ and $r_a > 0$, what does this imply about the change in the number of individuals with the $A$ and $a$ alleles over time? [1 mark]

12. What is $p=p(t)$ in equation 3.11b? Assuming that $0 \leq p(t) \leq 1$, for what values of $s_c$ does $p(t)$ increase? How can this condition on $s_c$, necessary for increasing $p(t)$, be understood in terms of $r_A$ and $r_a$? [2 marks]
