# Final project ideas

For your final project you may choose either option:

1. Review paper: Read and synthesize information on a new topic in population and evolutionary ecology that we have not considered in class.

or,

2. Analysis: Download and visualize a dataset relevant to population and evolutionary ecology. Discuss your graphs in the context of a principle in population and evolutionary ecology.

<span style="color: red;">Your paper/report should be no more than 10 pages single-spaced and excluding figures and references. Your paper does not need to be this long. Aim to make concise, well-argued points that are supported by citations.</span>

## Option 1: Review paper

Aim to write a final project that is similar in style to a paper that you would read in _Trends in Ecology and Evolution_ (TREE). The concepts that you cover, however, do not need to be as advanced as something that would appear in TREE. Use [Dias et al. 1996](https://www-sciencedirect-com.qe2a-proxy.mun.ca/science/article/pii/0169534796100379?via%3Dihub) _Sources and sinks in population biology_ as a guide for what a final project that is a _Review_ should aspire to look like. 

Topic ideas:

- Population dynamics in warming environments

- Population dynamics in seasonal environments

- Spatial population dynamics/metepopulations

- Evolution of sensence

- Evolution of body size

- Evolution of virulence

- Any of your own ideas, that are approved by Dr. Hurford or a teaching assistant.

## Option 2: Analysis
If you choose to do a final project that is an _Analysis_ you should use some of the exercises we have completed for class as a guide (for example, the Doubling time or Protection Island analyses - note that you will need to write your final project as a report, rather than a series of questions as the assignments typically are). You are expected to subset the data and make a graph. Be sure to decide on a principle from population biology or evolutionary ecology to discuss your analysis with respect to. For ideas you may wish to consult textbooks in these subject areas.

The style of your write up will be that of a regular scientific paper that includes an analysis, for example, [Suweis et al. 2013](https://www.pnas.org/content/110/11/4230): _The water-controlled wealth of nations_.

Some examples of data sources are:

- The [Environmental Data Initiative](https://portal.edirepository.org/nis/home.jsp)

- [Canopy arthropod dynamics from 1991-2017 at El Verde, Puerto Rico](https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-luq.96.2410865)

- [Zooplankton species in North Inlet Estuary, North Carolina](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-nin.2.1)

- _Ghosts of Habitats Past: Environmental Carry-Over Effects Drive Population Dynamics in Novel Habitat_ by Benjamin G. Van Allen and Volker H. W. Rudolf in The American Naturalist. [ [Article] ](https://www.journals.uchicago.edu/doi/10.1086/670127?mobileUi=0) [ [Data] ](https://datadryad.org/stash/dataset/doi:10.5061/dryad.t4g3r)

- The Yellow columbine (_Aquilegia chrysantha_) dataset associated with the [`popbio` package](https://cran.r-project.org/web/packages/popbio/index.html) for `R`. See `aq.census`.

- [Northern American Breeding Bird Survey](https://www.pwrc.usgs.gov/BBS/RawData/)

- [Fish populations in two small Appalachian streams](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-cwt.3026.13)

- [Grasshopper Dynamics for the Sevilleta National Wildlife Refuge, New Mexico](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-sev.106.214968)

- [Ebola data](https://apps.who.int/gho/data/node.ebola-sitrep.quick-downloads?lang=en)

- Or any of your own sources for population and evolutionary ecology data that you find.

## How to read scientific papers
Please consult [How to Read a Scientific Paper (2014)](https://www.research4life.org/blog/how-to-read-a-scientific-paper/) for the recommended approach to ‘reading’ journal articles. Steps 1,2, and 4 are good advice, but step 3 may not be relevant for some readings.

## Grading Rubric: Both Review and Analysis [55 marks]

1. The topic selected is within the scope of Population biology or evolutionary ecology. [5 marks]

1. The abstract follows [this](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjH9pDIya_sAhXig-AKHcB3BusQFjAAegQIBhAC&url=http%3A%2F%2Fwww.cbs.umn.edu%2Fsites%2Fdefault%2Ffiles%2Fpublic%2Fdownloads%2FAnnotated_Nature_abstract.pdf&usg=AOvVaw2FzVPRcUQOUX2zEJXld9LQ) format. [5 marks]

1. There is at least one paragraph towards the beginning of manuscript the overviews that main points that will be made. [5 marks]

1. At least 6 peer-reviewed articles are cited. [5 marks]

1. Citation format is consistent with the [_The American Naturalist_](https://www.journals.uchicago.edu/journals/an/instruct?mobileUi=0#manuscript-format) [5 marks]

1. Presentation, i.e., spelling, grammar etc. [5 marks]

1. The last paragraph or section of the report summarizes the main point. [5 points]

1. There is at least one figure or table, and these include a figure caption (for Review papers see further instructions below). [20 marks]

### Grading Rubric: Review only [55 marks]

1. The report is organized into sections. Each section has a clear point. [5 marks]

1. All sections together make a cohesive unit. [10 marks]

1. The citations are discussed in a way that demonstrates understanding of their content. [10 marks]

1. The citations are synthesized into a cohesive narrative. [10 marks]

1. Claims are fully supported by citations. [5 marks]

1. The report makes a clear point [5 marks]

1. The report provides an insightful narrative - arising from a thorough reading of the relevant peer-reviewed literature. [10 marks]

<span style="color: red;"> For the figure for the Review paper you may wish to illustrate the concepts underpinning your arguments visually. This might be similar to a graphical abstract, conceptual diagram, or an infographic. You may wish to sketch graphs to explain your ideas. Your diagram may be sketched by hand, photographed, and inserted into your write-up, or you might make it in Powerpoint or similar drawing software. You will be graded on how well the idea of the diagram communicates your arguments, not your graphical design skills. See [here](https://www-nature-com.qe2a-proxy.mun.ca/articles/s41467-018-07703-y/figures/1) for an example of a good figure (Figure 1 in Gokhale, S., Conwill, A., Ranjan, T. et al. Migration alters oscillatory dynamics and promotes survival in connected bacterial populations. Nat Commun 9, 5273 (2018). https://doi-org.qe2a-proxy.mun.ca/10.1038/s41467-018-07703-y) </span>

### Grading Rubric: Analysis only [55 marks]

1. An R Script that makes the figures in the report. [15 marks]

1. Report is organized into sections: 1) Introduction; 2) Data; 3) Analysis; and 4) Discussion. [5 marks]

1. The Introduction describes principles in population biology or evolutionary ecology and describes a hypothesis to be considered in light of the data visualization. [10 marks]

1. The Data section describes the dataset that will be analyzed and provides a link to where the data can be accessed. [5 marks]

1. Sufficient details are provided so that it is possible to evaluate the agreement between the formulation of the hypothesis and the data visualization that was done. [10 marks]

1. The Discussion outlines limitations of the analysis. If you would have liked to do another visualization or statistical analysis but do not know how to do it, mention this in the discussion - you will receive credit for having ideas of what to do, even if currently you don't know how to do it. [10 marks]
